import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './ui/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Radio Patio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid grid-cols-layout`}>
        <SideBar className="px-6 py-4 h-screen w-80" />
        <section className="flex flex-col px-6 py-4">{children}</section>
        {/* <SideBar className="px-6 py-4 h-screen w-80" /> */}
      </body>
    </html>
  )
}
